name: Publish to pypi
on:
  workflow_dispatch:
    inputs:
      upload:
        type: boolean
        description: upload to pypi

jobs:

  build:

    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install build
      run: |
        python -m pip install --upgrade build
    - name: Build sdist
      run: |
        python -m build --sdist
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-test:

    name: Publish to test.pypi
    runs-on: ubuntu-latest
    needs:
      - build

    environment:
      name: testpypi
      url: https://test.pypi.org/p/sdiff

    permissions:
      id-token: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to test.pypi.org
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  test-install:

    name: Test test.pypi
    runs-on: ubuntu-latest
    needs:
      - publish-to-test

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Wait 10s
      run: |
        sleep 10s
    - name: Install from pip
      run: pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple sdiff
    - name: Tests checkout
      uses: actions/checkout@v3
      with:
        ref: main
        sparse-checkout: 'tests'
    - name: Test
      run: |
        pip install pytest
        pytest -v --test-diff-renders -W ignore::pytest.PytestCollectionWarning

  publish-to-pypi:

    name: PUBLISH TO PYPI
    if: "${{ github.event.inputs.upload == 'true' }}"
    runs-on: ubuntu-latest
    needs:
      - test-install

    environment:
      name: pypi
      url: https://pypi.org/p/sdiff

    permissions:
      id-token: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to pypi.org
      uses: pypa/gh-action-pypi-publish@release/v1

  test-pypi:

    name: Test pypi
    if: "${{ github.event.inputs.upload == 'true' }}"
    runs-on: ubuntu-latest
    needs:
      - publish-to-pypi

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Wait 10s
      run: |
        sleep 10s
    - name: Install from pip
      run: pip install sdiff
    - name: Tests checkout
      uses: actions/checkout@v3
      with:
        ref: main
        sparse-checkout: 'tests'
    - name: Test
      run: |
        pip install pytest
        pytest -v --test-diff-renders -W ignore::pytest.PytestCollectionWarning
